class CallBackData:
    DOWNLOAD_LOGS = 'download_logs'
    GET_LOG = 'get_log'
    GET_REGISTRATION_WEBINAR = 'get_registration_webinar'
    GET_SELLER = 'get_seller'
    GET_LAST_EXCEL_FILE = 'get_last_excel_file'
    SHOW_LIST_FILE = 'show_list_file'
    SHOW_QUEUE = 'show_queue'
    ZOOM_MENU = 'zoom_menu'
    ADMIN_MENU = 'admin_menu'
    BACK_TO_MAIN = 'back_to_main'
    GET_LOG_PROGRAM = 'get_log_program'
    CLEAR_QUEUE = 'clear_queue'
    CLEAR_LOG = 'clear_log'
    CLEAR_COURSE = 'clear_course'
    SEND_TEST_EMAIL = 'send_test_email'
    GET_TEMPLATE_FILE_XLSX = 'get_template_file_xlsx'
    SHOW_REGISTRATION = 'show_registration'
    EDIT_REGISTRATION = 'edit_registration'
    DEL_REGISTRATION = 'delete_session_id_'

    FILE_DOWNLOAD_ = 'file_download_'
    FILE_DELETE_ = 'file_delete_'

